### ISSUE TITLE
Conditional visibility

### ISSUE THREAD

**Issue by mkaluza** [AndreiLux/Synapse#50]
A repeating pattern in settings is `if [ condition ] ..... fi`, where condition is usually 'fie X exists'. 

It would probably simplify the configs a bit if a "condition" field could be added. To make it simple for you and flexible for others, let it just be a string that is evaluated by shell and if the exit code is 0, condition is assumed to be true. That would allow the syntax:
{
    condition: "test -f /some/file".
    ....
}
And in a more advanced way
{
    condition: "test `cat /some/file` -gt some_value",
}
and so on.Of course it can also be a path to a script that can test for anything and has to 'exit 0' for condition to be true.

**Comment by AndreiLux** [comment]
This can't be done due to technical reasons on how the app builds the interface and uses the configuration DOM at boot. Keeping all possible elements in the JSON and having them evaluate at runtime creates much more overhead than having it don't once at config generation.

Again, if the config devs would try to generate the final file in a more cleaner way then it wouldn't be an issue at all.

**Comment by mkaluza** [comment]
But I wasn't talking about runtime condition evaluation (yeah, that would be cool, but that's a different story). This field could be evaluated during boot, so that it reads 'condition: 0' - it would still make syntax cleaner, and all the app has to do is to skip items with condition==false at startup.

**Comment by AndreiLux** [comment]
The app parses the whole configuration every time you launch it, not only at boot. I don't keep anything running in memory. To be able to evaluate a field it means that the whole JSON needs to be loaded. Configs like UKM have way too much "inactive" elements for this to run reasonably.
